<!DOCTYPE html>
<html lang="en">
<head>
    <title><%= meta.title %></title>
    <% partial('head') %>
    <link href="@@{top}css/api.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <% partial('sidebar') %>
    <div class="masthead">
        <% partial('nav') %>
    </div>
    <div class="content">
        <% content %>
    </div>
    <% partial('terms') %>
    <% partial('scripts') %>
</body>
</html>
