#!/bin/bash
#
#   Create or modify symlinks for the most recent installed versions of Appweb
#
#   Copyright (c) Embedthis Software LLC, 2003-2013. All Rights Reserved.
#

TASK=$1
PRODUCT=appweb

ROOT_PREFIX="${prefixes.root}"
BASE_PREFIX="${prefixes.base}"
STATE_PREFIX="${prefixes.state}"
APP_PREFIX="${prefixes.app}"
VAPP_PREFIX="${prefixes.vapp}"

BIN_PREFIX="${prefixes.bin}"
SBIN_PREFIX="${prefixes.sbin}"
ETC_PREFIX="${prefixes.etc}"
INC_PREFIX="${prefixes.inc}"
LIB_PREFIX="${prefixes.lib}"
MAN_PREFIX="${prefixes.man}"
WEB_PREFIX="${prefixes.web}"
LOG_PREFIX="${prefixes.log}"
SPL_PREFIX="${prefixes.spool}"
CACHE_PREFIX="${prefixes.cache}"

ABIN="${VAPP_PREFIX}/bin"
AINC="${VAPP_PREFIX}/in"

EXE=
PROGRAMS="appman appweb http auth esp"
LIBRARIES=""

if [ ! -x "${BIN_PREFIX}" ] ; then
    BIN_PREFIX="${ROOT_PREFIX}/usr/bin"
fi

prefix="${ROOT_PREFIX}/usr/lib/${PRODUCT}"
version=

if [ "$TASK" = "Remove" ] ; then
    for name in $PROGRAMS ; do
        rm -f "${BIN_PREFIX}/$name"
    done
    rm -rf  "${INC_PREFIX}/${PRODUCT}"
else
    for v in `ls $prefix 2>/dev/null | egrep -v '[a-zA-Z@!_\-]' | sort -n -r`
    do
        if [ -x "$prefix/$v/bin/appweb" ] ; then
            version=$v
            break
        fi
    done

    if [ "$version" = "" ] ; then
        latest=${prefix}
    else
        latest=${prefix}/$version
    fi
    rm -f "${prefix}/latest"
    ln -s "${latest}" "${prefix}/latest"
    bin="${latest}/bin"
    inc="${latest}/inc"
    man="${latest}/doc/man/man1"
    lib="${latest}/lib"

    [ ! -x "${BIN_PREFIX}" ] && mkdir -p "${BIN_PREFIX}"

    home=`pwd`
    for name in $PROGRAMS ; do
        name=${name}${EXE}
        rm -f "${BIN_PREFIX}/${name}"
        if [ -f "${bin}/${name}" ] ; then
            ln -s "${bin}/${name}" "${BIN_PREFIX}/${name}"
        fi
    done
    for name in $LIBRARIES ; do
        name=${name}
        rm -f "${LIB_PREFIX}/${name}*"
        if [ -f "${lib}/${name}*" ] ; then
            ln -s "${lib}/${name}*" "${LIB_PREFIX}/${name}"
        fi  
    done
    if [ -d "${inc}" ] ; then
        [ ! -x "${INC_PREFIX}" ] && mkdir -p "${INC_PREFIX}"
        rm -rf  "${INC_PREFIX}/${PRODUCT}"
        ln -s "${inc}" "${INC_PREFIX}/${PRODUCT}"
    fi
    if [ -d "${man}" ] ; then
        [ ! -x "${MAN_PREFIX}" ] && mkdir -p "${MAN_PREFIX}/man1"
        for f in ${man}/*.1.gz
        do
            name=`basename "$f"`
            rm -f "${MAN_PREFIX}/man1/${name}"
            ln -s "${f}" "${MAN_PREFIX}/man1/${name}"
        done
    fi
fi
